######################################################################
# Automatically generated by qmake (2.01a) Sat May 17 11:49:14 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += interface.h window.h window.cpp
SOURCES += interface.cpp main.cpp window.cpp
