######################################################################
# Automatically generated by qmake (2.01a) Sat May 17 19:16:38 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += info.h login.h menu.h studentMenu.h tutorMenu.h menu.cpp
SOURCES += info.cpp login.cpp main.cpp menu.cpp studentMenu.cpp tutorMenu.cpp
