######################################################################
# Automatically generated by qmake (2.01a) Wed May 14 21:13:32 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
